### PR TITLE
Fix for #14

### LINKED ISSUE #14: Setting multiple types for ArgOption of vector
Hello,

First of all, I love the ease and simplicity of this library; thank you for creating it.

Now, I have a simple project that I would like to have a certain flag, let's say `--convert` (or `-c`) that takes exactly four arguments (a directory and three files). Can I add type information in such a way that I get the following info when calling `get_help`?
```Usage: project [-c <directory> <file1> <file2> <file3>]```

Currently I get
```Usage: project [-c <directory file1 file2 file3> <directory file1 file2 file3> <directory file1 file2 file3>]```
which is not quite that helpful for a user, but also strange seeing as I don't see all arguments. (Shouldn't [zupply.cpp:12488](https://github.com/zhreshold/zupply/blob/master/src/zupply.cpp#L12488) be ```for (int i = 2; i < min_+1; ++i)```?

I sort of know/understand how to fix it in the `ArgOption::get_short_help()` function, but didn't want to make a pull request if this functionality already exists.

**EDIT:** Within the same context, I noticed an `ArgParser Error` is not being called for an invalid amount of arguments, unless I use `-c` multiple times. (Shouldn't [zupply.cpp:12809](https://github.com/zhreshold/zupply/blob/master/src/zupply.cpp#L12809) be ```if (o.count_ >= 1 && o.min_ > o.size_)```?)

### PR DESCRIPTION
**Pull request by RandyParedis**
- Multiple names can be set by using a newline
- Fixed some bugs that incorrectly show the max_ number of options and the lack of certain errors when using multi-option arguments

Fixes #14

### CODE REVIEW

File: src/zupply.cpp [hunk 1]
```diff
@@ -12480,19 +12493,72 @@ namespace zz
 
 			// type info
 			std::string st = "<" + type_ + ">";
+			std::vector<std::string> stvec;
+			if(type_.find('\n') != std::string::npos)
```
Comment (zhreshold) [inline src/zupply.cpp:12497]: I don't understand what this block for?

File: src/zupply.cpp [hunk 2]
```diff
@@ -12412,10 +12412,23 @@ namespace zz
 			const std::size_t alignment = 26;
 			std::string ret;
 
+			std::string type;
```
Comment (zhreshold) [inline src/zupply.cpp:12415]: You can do `type=fmt::rtrim(type_)` instead of loop: http://zhreshold.github.io/zupply/namespacezz_1_1fmt.html

**Review by zhreshold — COMMENTED** [review]
rest LGTM

File: src/zupply.cpp (hunk 2 above)
Comment (RandyParedis) [reply src/zupply.cpp:12415]: If I understand correctly what the `fmt::rtrim(type_)` does, I gather it removes all trailing whitespace.
But since I use a newline character (the normal `\n`, not those special CRLF find of newlines) to represent where to separate the different `type_` options, I just want to display it properly for the `get_info()` function without printing on too much new lines, which explains my need to replace **all** newlines that occur within this string and not just the trailing ones.

The newline character was chosen, because in my opinion it shouldn't normally be in the `type_` info. Also I wanted to keep this fix quite small and without too much adaptions, though I believe it might also be possible to store the `type_` as a vector of strings and discarding the idea of storing it within the same string, as I'm doing here.

File: src/zupply.cpp (hunk 1 above)
Comment (RandyParedis) [reply src/zupply.cpp:12497]: Due to the original "quick" solition that came to mind and the personal preference of not disturbing your code too much, I decided to use a separator character in the `type_` string (which was `\n`, as explained in a previous comment) to indicate each element in the list of possible types.

This block basically checks if a newline was used or not. If it's used, create a list of all the different types, otherwise, act normal. If the list is incomplete, fill with empty types until `max_`.
An empty list will change nothing to the current inner workings of the code, while it otherwise would display the types according to their occurence in the list. 
e.g. If the list contains `type1`, `type2` and `type3`; the option `-c` that uses it would show `-c <type1> <type2> <type3>` instead of `-c <type1 type2 type3> <> <>`

**Comment by zhreshold** [comment]
@RandyParedis Fair enough, could you please add some necessary TESTCASE and modify wiki if necessary, and we are good to merge!  Thanks for the contribution again.

**Comment by RandyParedis** [comment]
@zhreshold I added a TESTCASE to test my changes. As far as I can see, I don't have to change the wiki, but I can be wrong.

You're welcome and thank you again for the library.
